Repository fishi0x01/vsh, pull requests merged in 2021-02, with the labels that each got.

#75 Adjust documentation
  CHANGELOG.md
  README.md
  doc/commands/append.md
  doc/commands/cat.md
  doc/commands/cd.md
  doc/commands/cp.md
  doc/commands/grep.md
  doc/commands/ls.md
  doc/commands/mv.md
  doc/commands/replace.md
  doc/commands/rm.md
Labels: documentation

#83 hermetic builds, go version bump, arm64
  .github/workflows/ci.yml
  Makefile
  README.md
  go.mod
  go.sum
  test/util/util.bash
Labels: enhancement

#85 Fix no-op
  CHANGELOG.md
  main.go
Labels: bug

#84 Add thread-safe cache
  Makefile
  client/cache.go
  client/client.go
  client/list.go
  client/traverse.go
  client/type.go
  test/run-all-tests.sh
  test/suites/commands/append.bats
  test/suites/commands/cat.bats
  test/suites/commands/cd.bats
  test/suites/commands/cp.bats
  test/suites/commands/grep.bats
  test/suites/commands/ls.bats
  test/suites/commands/mv.bats
  test/suites/commands/replace.bats
  test/suites/commands/rm.bats
  test/suites/concurrency/mv.bats
  test/suites/edge-cases/false-commands.bats
  test/suites/edge-cases/kv-migrations-with-append.bats
  test/suites/edge-cases/kv-migrations-with-cp.bats
  test/suites/edge-cases/kv-migrations-with-mv.bats
  test/suites/edge-cases/logging.bats
  test/suites/edge-cases/params.bats
  test/suites/edge-cases/print-version.bats
  test/suites/past-issues/45_rm-bug.bats
  test/util/common.bash
  test/util/concurrency-setup.bash
  test/util/standard-setup.bash
Labels: enhancement

#91 Adding dry-run/confirm flags to the 'add' command
  cli/add.go
  doc/commands/add.md
  test/suites/commands/add.bats
Labels: enhancement

#92 Fix caching behavior
  CHANGELOG.md
  completer/completer.go
  main.go
Labels: bug
